// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAZlC_3EVSqTDm9AjBuuW4d8bJMuwY9FE',
    appId: '1:893425614933:android:c868bb308f347107f1d4dc',
    messagingSenderId: '893425614933',
    projectId: 'talentturbo-cddd3',
    storageBucket: 'talentturbo-cddd3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpmWRVsP1GV55_jx3o-Hys958KvESnWmo',
    appId: '1:893425614933:ios:7422001eb19977f3f1d4dc',
    messagingSenderId: '893425614933',
    projectId: 'talentturbo-cddd3',
    storageBucket: 'talentturbo-cddd3.firebasestorage.app',
    iosClientId: '893425614933-9j08bkqtfp9opclpq2dse4cuau7cvjh6.apps.googleusercontent.com',
    iosBundleId: 'com.talentturbo.referral.talentTurboNew',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlzxQ-GrEz4y3wfINP6d6Luf6hzNAOQQU',
    appId: '1:893425614933:web:a05e76202b62f3d5f1d4dc',
    messagingSenderId: '893425614933',
    projectId: 'talentturbo-cddd3',
    authDomain: 'talentturbo-cddd3.firebaseapp.com',
    storageBucket: 'talentturbo-cddd3.firebasestorage.app',
    measurementId: 'G-SCRCT732MH',
  );

}